# Generated by Django 3.2 on 2022-11-13 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='게시판 이름')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='게시판 생성일')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('is_superuser', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='글 제목')),
                ('content', models.TextField(verbose_name='글 내용')),
                ('written_date', models.DateTimeField(auto_now_add=True, verbose_name='글 작성일')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='글 수정일')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice_board.subject', verbose_name='게시판 이름')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice_board.user', verbose_name='작성자')),
            ],
        ),
    ]
